btl/btl/btl/Models/PostCategory.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace btl.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class PostCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PostCategory()
        {
            this.Posts = new HashSet<Post>();
        }
        [DisplayName("Mã loại bài viết")]
        public int ID { get; set; }
[DisplayName("Tên loại bài viết")]
        public string Name { get; set; }
[DisplayName("Tên khác")]
        public string Alias { get; set; }
[DisplayName("Mô tả")]
        public string Description { get; set; }
[DisplayName("Thứ tự")]
        public Nullable<int> DisplayOrder { get; set; }
[DisplayName("Ảnh")]
        public string Image { get; set; }
[DisplayName("Đề xuất")]
        public Nullable<bool> HomeFlag { get; set; }
[DisplayName("Ngày tạo")]
        public Nullable<System.DateTime> CreatedDate { get; set; }
[DisplayName("Người tạo")]
        public string CreatedBy { get; set; }
        public string MetaKeyword { get; set; }
        public string MetaDescription { get; set; }
[DisplayName("Trạng thái")]
        public bool Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Posts { get; set; }
    }
}

btl/btl/btl/Areas/Area/Controllers/PostCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using btl.Models;

namespace btl.Areas.Area.Controllers
{
    public class PostCategoriesController : Controller
    {
        private DshopEntities db = new DshopEntities();

        // GET: Area/PostCategories
        public ActionResult Index()
        {
            return View(db.PostCategories.ToList());
        }

        // GET: Area/PostCategories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PostCategory postCategory = db.PostCategories.Find(id);
            if (postCategory == null)
            {
                return HttpNotFound();
            }
            return View(postCategory);
        }

        // GET: Area/PostCategories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Area/PostCategories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Alias,Description,DisplayOrder,Image,HomeFlag,CreatedDate,CreatedBy,MetaKeyword,MetaDescription,Status")] PostCategory postCategory, HttpPostedFileBase Image)
        {
            string _FileName = "";
            string _path = "";
            try
            {
                if (Image.ContentLength > 0)
                {
                    _FileName = Path.GetFileName(Image.FileName);
                    _path = Path.Combine(Server.MapPath("~/Uploadimg"), _FileName);
                    Image.SaveAs(_path);
                }
            }
            catch
            {
            }
            if (ModelState.IsValid)
            {
                postCategory.Image = _FileName;
                db.PostCategories.Add(postCategory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(postCategory);
        }

        // GET: Area/PostCategories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PostCategory postCategory = db.PostCategories.Find(id);
            if (postCategory == null)
            {
                return HttpNotFound();
            }
            return View(postCategory);
        }

        // POST: Area/PostCategories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Alias,Description,DisplayOrder,Image,HomeFlag,CreatedDate,CreatedBy,MetaKeyword,MetaDescription,Status")] PostCategory postCategory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(postCategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(postCategory);
        }

        // GET: Area/PostCategories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PostCategory postCategory = db.PostCategories.Find(id);
            db.PostCategories.Remove(postCategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // POST: Area/PostCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PostCategory postCategory = db.PostCategories.Find(id);
            db.PostCategories.Remove(postCategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

btl/btl/btl/Areas/Area/Views/PostCategories/Create.cshtml
@model btl.Models.PostCategory

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Area/Views/Shared/_Layout.cshtml";
}

<h2>Thêm loại bài viết</h2>

@using (Html.BeginForm("Create", "PostCategories", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*nội dung bên trái*@
        <div class="col-md-6" style="float:left">
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Alias, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Alias, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Alias, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-10">
                    <textarea class="form-control" name="Description" id="inpData"></textarea>
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        @*nội dung bên phải*@
        <div class="col-md-6" style="float:right">
            <div class="form-group">
                @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-5">
                    <input type="file" id="Image" name="Image" multiple />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MetaKeyword, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MetaKeyword, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MetaKeyword, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MetaDescription, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MetaDescription, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MetaDescription, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Status)
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Lưu" class="btn btn-primary" />
                    @Html.ActionLink("Trở lại", "Index", null, new { @class = "btn btn-warning" })
                </div>
            </div>
        </div>
    </div>




}
@section scripts{
    <script>
        CKEDITOR.replace('inpData')
    </script>
}

btl/btl/btl/Areas/Area/Views/PostCategories/Delete.cshtml
@model btl.Models.PostCategory

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Area/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PostCategory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Alias)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Alias)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DisplayOrder)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DisplayOrder)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HomeFlag)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HomeFlag)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MetaKeyword)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MetaKeyword)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MetaDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MetaDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

btl/btl/btl/Areas/Area/Views/PostCategories/Details.cshtml
@model btl.Models.PostCategory

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Area/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>PostCategory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Alias)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Alias)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DisplayOrder)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DisplayOrder)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HomeFlag)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HomeFlag)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MetaKeyword)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MetaKeyword)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MetaDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MetaDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

btl/btl/btl/Areas/Area/Views/PostCategories/Edit.cshtml
@model btl.Models.PostCategory

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Area/Views/Shared/_Layout.cshtml";
}

<h2>Sửa loại bài viết</h2>

@using (Html.BeginForm("Create", "PostCategories", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*nội dung bên trái*@
        <div class="col-md-6" style="float:left">
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Alias, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Alias, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Alias, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-10">
                    <textarea class="form-control" name="Description" id="inpData">@Model.Description</textarea>
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        @*nội dung bên phải*@
        <div class="col-md-6" style="float:right">
            <div class="form-group">
                @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-5">
                    <input type="file" id="Image" name="Image" multiple />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MetaKeyword, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MetaKeyword, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MetaKeyword, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MetaDescription, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MetaDescription, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MetaDescription, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Status)
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Lưu" class="btn btn-primary" />
                    @Html.ActionLink("Trở lại", "Index", null, new { @class = "btn btn-warning" })
                </div>
            </div>
        </div>
    </div>




}
@section scripts{
    <script>
        CKEDITOR.replace('inpData')
    </script>
}

btl/btl/btl/Areas/Area/Views/PostCategories/Index.cshtml
@model IEnumerable<btl.Models.PostCategory>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Area/Views/Shared/_Layout.cshtml";
}

<h2>Quản lý danh sách loại bài viết</h2>

<p>
    @Html.ActionLink(" Tạo mới", "Create", null, new { @class = "btn btn-warning fa fa-plus" })
</p>
<table class="table table-bordered table-striped" id="dataTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>

            <th></th>
        </tr>
    </thead>
    
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <img src="/Uploadimg/@item.Image" style="width:100px;height:100px" />
            </td>
            <td>
                @Html.Raw(@item.Description)
            </td>
            <td>
                @Html.ActionLink(" ", "Edit", new { id = item.ID }, new { @Class = "btn btn-warning fa fa-pencil" })
                @Html.ActionLink(" ", "Details", new { id = item.ID }, new { @Class = "btn btn-primary fa fa-eye" })
                @Html.ActionLink(" ", "Delete", new { id = item.ID }, new { @Onclick = "return confirm('Bạn có chắc muốn xóa không?')", @Class = "btn btn-danger fa fa-trash" })
            </td>
        </tr>
        }

    </tbody>
    
</table>